- src/pixie-threads.c
- src/pixie-threads.h
Fixes Debian#773786 and enables support on non-ARM,
Non-x86, and kFreeBSD architectures.
> Fix FTBFS on most Debian architectures

- src/string_s.h
Patch applied in Debian to solve FTBFS with the GCC's new version. The original bug report is available here:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=777997
Thanks for considering.
> Fix build failure with GCC 5

- src/main-conf.c
- src/main-globals.h
- src/main-status.c
- src/main.c
- src/masscan.h
- src/output.c
- src/rawsock.c
32dfd86 adds an extra parameter which prevents masscan from sending status updates to the output to simplify automated handling
ff34bb0 prevents masscan from closing when waiting for the last packets if it has yet to receive a SIGINT, this prevents a race condition where the user may send a SIGINT before realizing this.
32bd94b echoes the number of retries in paused.conf as otherwise the user will get bogus results on resumption
a43ab2b fixes issues with the echoing of ports to paused.conf
> Various fixes involving port handling and resumption

- src/main-conf.c
- which means show host up, port open and port closed info. And most important, it means don't throw an en error when show = all is encountered in a config file
things:
- Closed ports
- Open ports
- Up hosts
Note that the following two are equivalent in the config file:
show = open,closed,host
show = all
Without this patch, show = all in a config file threw an error. I believe this is the correct way to fix it, though I wasn't sure if show_open was necessary since it is set by default. I chose to go with setting show_open because if a user did:
...
show = closed
show = all
..
... in a config file, the resulting behavior should (I think) be show = all, so show_open would have to be restored to its default value.
Pointed out by blkshv:
https://github.com/robertdavidgraham/masscan/issues/190 …
> [PATCH] BUGFIX to make show = all in config files work correctly

- README.md
Was about to complain that the my `zc:enp1s0` device wasn't being picked up, until I opened up GitHub and saw you beat me to it yesterday. =)
> Updated README for ZC.

- src/out-json.c
Fixed JSON output to include wrapping the complete set of {..}'s in […] bracket and removing the last line which didn't fit the avp syntax
> JSON Output Fix

- src/pixie-backtrace.c
when compiled in openwrt sdk environment, will find no find execinfo.h error
> fix openwrt compile error

- Makefile
The order of object files is derived from the list of source files,
which has no deterministic order.
Sort the list to enable reproducible building.
> Sort list of source files for deterministic linking order

- src/main-dedup.c
- src/proto-icmp.c
Implement deduplication for ICMP replies in the same style as SYN/ACK replies. This is not a perfect process and the effectiveness is determined by a bucket size. I've also increased the bucket size from 4k to 64k.
This is useful for performing ping only sweeps with --retry for extra reliability where packet loss might occur.
The bucket size affects the SYN/ACK deduplication as well due to its location in the code and it didn't seem appropriate to split them apart into two different parameters.
> [PATCH] FEATURE: Deduplicate ICMP like SYN/ACK and increase deduplication bucket size

- src/main-conf.c
This fixes -iL <file> to behave as expected and perform a ping scan
of the ranges in the file. Before it seemed to think there was
not scan activity to perform.
masscan -iL <file> --ping 
With this small patch, this now works, in master it fails.This is because it failed to set a flag that told masscan that it should do something (move on to the scanning stage) after parsing the commandline arguments.
> [PATCH] BUGFIX: The '-iL' option is completely broken when using --ping

- src/main.c
Normally, masscan reports a SYN Stealth scan is starting regardless of what
options have been passed on the command line- i.e. UDP, TCP, ICMP, ARP, etc.
This patch just provides a clear banner when starting an ICMP only scan.
This change ONLY affects ICMP only scans. When performing a SYN scan,
SYN + UDP scan, or SYN + UDP + ICMP scan, the original behavior stays the 
same and reports a SYN Stealth scan as it always has.
This is just a cosmetic change to make it clearer that you didn't
invoke the scan incorrectly when trying to only perform a simple ping sweep.
> [PATCH] BUGFIX: fixed the boot status output to have correct information when an ICMP only scan is starting

- src/out-unicornscan.c
In the initial implementation, I accidentally left a hardcoded 'open' in
the fprintf, which made results for --show closed broken.
This uses status_string(status) instead of hard coding "open" into the
status value.
> [PATCH] BUGFIX: Unicornscan output so that 'closed' ports are reported as 'closed' instead of 'open'

- README.md
- doc/masscan.8.markdown
RFC1918 specifies 172.16.0.0/12 (rather than /20 or /14)
https://tools.ietf.org/html/rfc1918
> Fix RFC1918 netmask (172.16.0.0/12)

- src/rawsock.c
masscan would crash if the user specifies the --pfring option but has not installed pfring dna adapter.
Just a thought here. Since masscan defaults to pfring based capture, is this option really required?
Perhaps an option "--nopfring" would be more useful.
> Fix for segmentation fault #165

- src/main.c
Suggestion to fix issue #505 (see issue discussion for more details about the round value).
Changing the number of rounds for `blackrock` seems to:
- increase the distribution of scanned IP in a partial scan (*e.g.*, after 10% of the scan)
- have a very low impact on scanning rate.
> Improve statistical distribution of partial scan

- src/stub-pcap.c
For some reason this function has an incorrect name `pcap_datalink_val_toName` - in `libpcap` it's defined as `pcap_datalink_val_to_name`, and even in masscan itself it's properly referenced:
Found this when trying to build masscan with static `libpcap`
> Fix function name in stub-pcap

- src/main-conf.c
The parameter of max-rate is double type. We can input command like this.
masscan -p 80,8080 10.0.0.0/8 -oX /home/scan.xml --max-rate 400.12345
I found this decimal calculation wrong.
> Floating-point character conversion error

- src/out-redis.c
In the `redis_out_close()`:
1) send `QUIT` instead of `PING` to the connected Redis server for disconnection. The `PING` was a wrong command here. 
2) expect `+OK` or `:0` as legitimate responses from the server, other than `+PONG`.
This resolves the issue #445 
Tested with the latest stable version of Redis server (5.0.5).
> Fixes errors in redis_out_close and issue #445

- src/out-tcp-services.c
- src/pixie-threads.c
Termux doesn't seem to have `getservbyport_r` and `pthread_setaffinity_np` so I added checks for the `__TERMUX__`  define.
Compilation output before the patch:
```
/data/data/com.termux/files/usr/bin/ld: tmp/out-tcp-services.o: in function `tcp_service_name':
/data/data/com.termux/files/home/masscan/src/out-tcp-services.c:33: undefined reference to `getservbyport_r'
/data/data/com.termux/files/usr/bin/ld: tmp/out-tcp-services.o: in function `udp_service_name':
/data/data/com.termux/files/home/masscan/src/out-tcp-services.c:65: undefined reference to `getservbyport_r'
/data/data/com.termux/files/usr/bin/ld: tmp/pixie-threads.o: in function `pixie_cpu_set_affinity':
/data/data/com.termux/files/home/masscan/src/pixie-threads.c:86: undefined reference to `pthread_setaffinity_np'
clang-11: …
```
> Fix compilation for Termux

- src/stub-pcap.h
OpenBSD uses bpf_timeval (uint32_t tv_sec and tv_usec), with this changed masscan works on OpenBSD as long as you set gateway ip/mac manually.
> handle OpenBSD's bpf_timeval

- src/main-conf.c
This is for #559 
The cli/conf handling code was significantly cleaned up recently (thanks for all that effort @robertdavidgraham) and that fixed a whole handful of issues. That made a huge improvement and fixed at least 3 other (similar) issues, but it looks like this shook out of it all
Like the other options issues, it's an easy fix to test and review:
1. An entry got left out from the `config_parameters[]` for `nocapture` option. The `capture` and `nocapture` options are both handled by `SET_capture`, so the code was there, the dispatch table was just ignorant. So I added a line for `nocapture` to send it there when it encounters that option
2. Within the `"nocapture"` checking block, the `"servername"` case specifically was missing, though the others were there. I just added that in …
> Fix for #559- (resume broken for most uses, copy/pasta to fix --nocapture=servername)

- src/syn-cookie.c
Addressing issue #99.
If this code is run on systems without *NIX environments and for which "/" could be a file and not a directory, an fclose call is needed.
> Ensure fclose just in case code is run on non *NIX systems

- src/proto-dns.c
The value ```txtlen``` is used to decide how many bytes of ```px+offset``` are
to be read into the banner buffer. The ```txtlen``` value is taken from the DNS
response without validation. 
A malicious server setting the ```txtlen``` to the max possible value (0xff)
would still not be able to overflow the banner buffer. 
At worst, a malicious DNS server would set ```txtlen``` to 0xff and provide an
empty banner. As a result the 0xff bytes of memory after ```px``` would be
saved as the DNS banner. This leaks memory but only to the person running the
scan.
A check was added to reduce ```txtlen``` if it is too large. Alternatively a
```return 0;``` could be used. 
I moved the line ```offset += 11;``` up to keep the validation checks together
and avoid adding 11 to the ```txtlen``` check.
> fix dns banner corruption from invalid txtlen

- src/string_s.h
MSVC++ 14.15 _MSC_VER == 1915 (Visual Studio 2017 version 15.8)
MSVC++ 14.14 _MSC_VER == 1914 (Visual Studio 2017 version 15.7)
MSVC++ 14.13 _MSC_VER == 1913 (Visual Studio 2017 version 15.6)
MSVC++ 14.12 _MSC_VER == 1912 (Visual Studio 2017 version 15.5)
MSVC++ 14.11 _MSC_VER == 1911 (Visual Studio 2017 version 15.3)
MSVC++ 15.0 _MSC_VER == 1910 (Visual Studio 2017)
> add suppot for visual studio 2017

- src/main.c
After this commit 952755771ab8065c052cdf4b6d18041435b2d661 to fix issue #574, the scan will not complete because `min_index` will not get higher than `range` in https://github.com/robertdavidgraham/masscan/blob/master/src/main.c#L1419.
> Fix scan not finished for retries > 0 (#574)

- src/main.c
- src/massip-addr.c
Looks like a copy paste error for the argument.
Also fixed ipv6 address formatter, it was checking for values outside the address buffer and sometimes missing printing the last : 
Would you be interested in a banner parser for Bitcoin?
> Fix hello-timeout argument configuration and ipv6 formatter

- src/stub-pcap.c
On CentOS7 libpcap is installed as libpcap.so.1, adding thisto possible names
> Update stub-pcap.c to support centos 7

- doc/masscan.8.markdown
`--retries` actually accepts a numeric argument.
> Fixed documentation for `--retries`

- src/main.c
`increment` and `start` variables in `transmit_thread` are initialized with incorrect values that cause duplicate transmissions.
> Fix increment and start initialization in TX thread

- LICENSE
- README.md
The LICENSE file mostly contained the standard license header for the agpl-3.0-only license. This commit adds the standard license header to the readme file under a new License header at the bottom and applies the complete text of the AGPL into the license file.
In addition to correctly applying the license, this patch will help forges such as GitHub correctly identify the license and present this information within the first page view of the project.
> agpl-3.0-only

- src/proto-snmp.c
This change fixes code which was supposed to output SNMP INTEGER32 VarBind into `banner`.
> Fix printing SNMP Integer varbind into banner

- src/main-conf.c
- src/main.c
- src/masscan.h
- src/out-redis.c
- src/output.c
- src/output.h
Auth-enabled Redis is always used in distributed scan scenarios.
> Add support for redis auth

- src/main-conf.c
- src/main.c
- src/masscan.h
This PR does 2 things:
* it aims to addresses Issue #677 -- see details below
* it adds a new CLI option `--echo-cidr` to output IP addresses at CIDR format (`X.Y.Z.T/M`) instead of range format (`X1.Y1.Z1.T1-X2.Y2.Z2.T2`) -- see details below
These two things are in one PR because they modify the same parts of the code - two different PR would lead to merge conflicts.
---
* fix bug in "small" CIDR ranges (/65../128)
* handle "large" CIDR ranges (/0../63)
```
$ bin/masscan --echo :: ::1
seed = 6069904213427194911
rate = 100       
shard = 1/1
nocapture = servername
nocapture = servername
ports = 
range = ::/127
```
```
$ bin/masscan --echo 2000:: 2000::1
seed = 2054565738792150746
rate = 100       
shard = 1/1
nocapture = servername
nocapture = servername
ports = 
range = 2000::/127
``` …
> Fix bug in --echo for IPv6 ranges & add --echo-cidr option

- src/smack1.c
Current masscan has a build issue on FreeBSD aarch64.
Error log is following:
src/smack1.c:130:16: error: unrecognized instruction mnemonic, did you mean: mrs, msr, smc?
asm volatile("mrc p15, 0, %0, c9, c14, 0" : "=r"(pmuseren));
^
<inline asm>:1:2: note: instantiated into assembly here
mrc p15, 0, x8, c9, c14, 0
^
src/smack1.c:132:18: error: unrecognized instruction mnemonic, did you mean: mrs, msr, smc?
asm volatile("mrc p15, 0, %0, c9, c12, 1" : "=r"(pmcntenset));
^
<inline asm>:1:2: note: instantiated into assembly here
mrc p15, 0, x8, c9, c12, 1
^
src/smack1.c:134:20: error: unrecognized instruction mnemonic, did you mean: mrs, msr, smc?
asm volatile("mrc p15, 0, %0, c9, c13, 0" : "=r"(pmccntr));
^
<inline asm>:1:2: note: instantiated into assembly here
mrc p15, 0, x8, c9, c13, 0
^ …
> fix FreeBSD aarch64 build issue

- src/masscan-app.c
`{"ssh2", PROTO_SSH2}` is listed twice.
> Removed a duplicate list entry for ssh2.

- src/main-conf.c
It's customary that the `usage:` string is also included in the `--help` output.
> Also include the usage: string in the --help output.

- src/main.c
- src/masscan-app.c
- src/masscan-app.h
The PROTO_ ID should only be added on the end, not in the middle. So I moved the new PROTO_VNC_INFO.
Also, I added a selftest so this mistake won't happen again.
> Integration

- src/main.c
- src/massip-addr.c
- src/massip-addr.h
I split out the oddly named test function for address formatting (named for ipv6, but had only a single test case, for ipv4)
I did this when trying to track down #796
Unfortunately, I didn't find any issues .... if anyone wants to take a look, feel free. I think more information is needed to reproduce the behavior that is reported there
> add suite of ipv6 formatting tests, related to #796

- src/proto-banout.c
Not really sure how nobody noticed, but at least on my
> gcc version 14.2.0 (Debian 14.2.0-16)
```sh
$ ./bin/masscan --selftest
======================================================================
Segmentation fault: please post this backtrace to:
https://github.com/robertdavidgraham/masscan/issues
======================================================================
13: [./bin/masscan(+0xa871) [0x55e644345871]]
?? ??:0
[....]
```
`marker` is consumed when used in the first `vnsprintf`, resulting in a segfault in the second. See https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/va-arg-va-copy-va-end-va-start?view=msvc-170
> Fix bug in banout_vprintf
